(*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*)

let rec fib =
    seq {
        yield 1UL
        yield! Seq.scan (+) 2UL fib
    }

let solve =
    fib
    |> Seq.filter (fun n -> n % 2UL = 0UL)
    |> Seq.takeWhile ((>) 4_000_000UL)
    |> Seq.sum
